
title: Reel Jekyll Template
description: A minimal, functional theme for running a paid-membership publication on Ghost.
logo: assets/images/logo.svg
email: your-email@example.com
description: Some descriptio
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

plugins:
  - jekyll-feed

#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
