
title: Reel Jekyll Template
hero_title : This is Mukesh Salesforce Consulting
description: A minimal, functional theme for running a paid-membership publication on Ghost.
logo: assets/images/logo.svg
email: your-email@example.com
description: Lorem
url: 'https://reel.imswarnil.com' # the subpath of your site, e.g. /blog # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag


sass:
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
